### ISSUE TITLE
Error Installing Theme

### ISSUE THREAD

**Issue by DanPhonovation** [nephila/nephila-taiga-theme#1]
Getting an error when attempting to install this:

```
/home/taiga/taiga-front-dist/gulp-utils.js:16
            if (themesSequence[i].name === name) {
                                 ^

TypeError: Cannot read property 'name' of undefined
  at searchIndex (/home/taiga/taiga-front-dist/gulp-utils.js:16:34)
  at Object.Theme.obj.set (/home/taiga/taiga-front-dist/gulp-utils.js:59:31)
  at Object.<anonymous> (/home/taiga/taiga-front-dist/gulpfile.js:45:12)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
  at module.exports (/usr/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:190:9)
  at /usr/lib/node_modules/gulp/node_modules/liftoff/index.js:164:9
  at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:110:14
  at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:38:12
  at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:49:7
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickCallback (internal/process/next_tick.js:104:9)
  at Module.runMain (module.js:606:11)
  at run (bootstrap_node.js:389:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:502:3

```

I can take the if statement out and "get past it" but then I get a similar one:

```
(taiga) [taiga@taiga themes]$ gulp --theme nephila
[15:12:49] Working directory changed to ~/taiga-front-dist
/home/taiga/taiga-front-dist/gulpfile.js:92
paths.sass_watch = paths.sass.concat(themes.current.customScss);
                                                   ^

TypeError: Cannot read property 'customScss' of undefined
  at Object.<anonymous> (/home/taiga/taiga-front-dist/gulpfile.js:92:52)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
  at module.exports (/usr/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:190:9)
  at /usr/lib/node_modules/gulp/node_modules/liftoff/index.js:164:9
  at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:110:14
  at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:38:12
  at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:49:7
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickCallback (internal/process/next_tick.js:104:9)
  at Module.runMain (module.js:606:11)
  at run (bootstrap_node.js:389:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:502:3
```

**Comment by uhlhosting** [comment]
guess is not supported since it has no updated whats so ever.

**Comment by yakky** [comment]
Yes, sorry, but this package is no longer supported
I'm archiving this to make this clear
Thanks both for the interest in this package
